[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"
  base = "docs"

[context.production.environment]
  NODE_VERSION = "18"  # Specify the Node.js version, if needed

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200
