[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"

[context.production.environment]
  NETLIFY_SKIP_COMPOSER_INSTALL = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200
