name: Compatibility Check

on:
  push:
    branches:
      - main
      - refactor/**
      - feature/**
      - fix/**

jobs:
  check-compatibility:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} on ${{ matrix.os }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, json, openssl
          coverage: none

      - name: Install Composer
        run: composer self-update

      - name: Create Laravel project
        run: composer create-project --prefer-dist laravel/laravel laravel-project "${{ matrix.laravel }}" --no-progress --no-interaction

      - name: Navigate to Laravel project
        run: cd laravel-project

      - name: Add your package to composer.json
        run: |
          composer config repositories.local path ../
          composer require jerome/fetch-php --no-update

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-${{ matrix.stability }}

      - name: Run Laravel tests (if applicable)
        run: php artisan test
